// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ortools/util/int128.proto
// Protobuf C++ Version: 5.29.3

#ifndef ortools_2futil_2fint128_2eproto_2epb_2eh
#define ortools_2futil_2fint128_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ortools_2futil_2fint128_2eproto OR_PROTO_DLL

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct OR_PROTO_DLL TableStruct_ortools_2futil_2fint128_2eproto {
  static const ::uint32_t offsets[];
};
OR_PROTO_DLL extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ortools_2futil_2fint128_2eproto;
namespace operations_research {
class Int128;
struct Int128DefaultTypeInternal;
OR_PROTO_DLL extern Int128DefaultTypeInternal _Int128_default_instance_;
}  // namespace operations_research
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace operations_research {

// ===================================================================


// -------------------------------------------------------------------

class OR_PROTO_DLL Int128 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:operations_research.Int128) */ {
 public:
  inline Int128() : Int128(nullptr) {}
  ~Int128() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Int128* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Int128));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Int128(
      ::google::protobuf::internal::ConstantInitialized);

  inline Int128(const Int128& from) : Int128(nullptr, from) {}
  inline Int128(Int128&& from) noexcept
      : Int128(nullptr, std::move(from)) {}
  inline Int128& operator=(const Int128& from) {
    CopyFrom(from);
    return *this;
  }
  inline Int128& operator=(Int128&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Int128& default_instance() {
    return *internal_default_instance();
  }
  static inline const Int128* internal_default_instance() {
    return reinterpret_cast<const Int128*>(
        &_Int128_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Int128& a, Int128& b) { a.Swap(&b); }
  inline void Swap(Int128* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Int128* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Int128* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Int128>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Int128& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Int128& from) { Int128::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Int128* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "operations_research.Int128"; }

 protected:
  explicit Int128(::google::protobuf::Arena* arena);
  Int128(::google::protobuf::Arena* arena, const Int128& from);
  Int128(::google::protobuf::Arena* arena, Int128&& from) noexcept
      : Int128(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHighFieldNumber = 1,
    kLowFieldNumber = 2,
  };
  // int64 high = 1;
  void clear_high() ;
  ::int64_t high() const;
  void set_high(::int64_t value);

  private:
  ::int64_t _internal_high() const;
  void _internal_set_high(::int64_t value);

  public:
  // uint64 low = 2;
  void clear_low() ;
  ::uint64_t low() const;
  void set_low(::uint64_t value);

  private:
  ::uint64_t _internal_low() const;
  void _internal_set_low(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:operations_research.Int128)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Int128& from_msg);
    ::int64_t high_;
    ::uint64_t low_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2futil_2fint128_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Int128

// int64 high = 1;
inline void Int128::clear_high() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.high_ = ::int64_t{0};
}
inline ::int64_t Int128::high() const {
  // @@protoc_insertion_point(field_get:operations_research.Int128.high)
  return _internal_high();
}
inline void Int128::set_high(::int64_t value) {
  _internal_set_high(value);
  // @@protoc_insertion_point(field_set:operations_research.Int128.high)
}
inline ::int64_t Int128::_internal_high() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.high_;
}
inline void Int128::_internal_set_high(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.high_ = value;
}

// uint64 low = 2;
inline void Int128::clear_low() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.low_ = ::uint64_t{0u};
}
inline ::uint64_t Int128::low() const {
  // @@protoc_insertion_point(field_get:operations_research.Int128.low)
  return _internal_low();
}
inline void Int128::set_low(::uint64_t value) {
  _internal_set_low(value);
  // @@protoc_insertion_point(field_set:operations_research.Int128.low)
}
inline ::uint64_t Int128::_internal_low() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.low_;
}
inline void Int128::_internal_set_low(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.low_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace operations_research


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ortools_2futil_2fint128_2eproto_2epb_2eh
