// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ortools/constraint_solver/search_limit.proto
// Protobuf C++ Version: 5.29.3

#ifndef ortools_2fconstraint_5fsolver_2fsearch_5flimit_2eproto_2epb_2eh
#define ortools_2fconstraint_5fsolver_2fsearch_5flimit_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ortools_2fconstraint_5fsolver_2fsearch_5flimit_2eproto OR_PROTO_DLL

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct OR_PROTO_DLL TableStruct_ortools_2fconstraint_5fsolver_2fsearch_5flimit_2eproto {
  static const ::uint32_t offsets[];
};
OR_PROTO_DLL extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ortools_2fconstraint_5fsolver_2fsearch_5flimit_2eproto;
namespace operations_research {
class RegularLimitParameters;
struct RegularLimitParametersDefaultTypeInternal;
OR_PROTO_DLL extern RegularLimitParametersDefaultTypeInternal _RegularLimitParameters_default_instance_;
}  // namespace operations_research
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace operations_research {

// ===================================================================


// -------------------------------------------------------------------

class OR_PROTO_DLL RegularLimitParameters final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:operations_research.RegularLimitParameters) */ {
 public:
  inline RegularLimitParameters() : RegularLimitParameters(nullptr) {}
  ~RegularLimitParameters() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RegularLimitParameters* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RegularLimitParameters));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RegularLimitParameters(
      ::google::protobuf::internal::ConstantInitialized);

  inline RegularLimitParameters(const RegularLimitParameters& from) : RegularLimitParameters(nullptr, from) {}
  inline RegularLimitParameters(RegularLimitParameters&& from) noexcept
      : RegularLimitParameters(nullptr, std::move(from)) {}
  inline RegularLimitParameters& operator=(const RegularLimitParameters& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegularLimitParameters& operator=(RegularLimitParameters&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RegularLimitParameters& default_instance() {
    return *internal_default_instance();
  }
  static inline const RegularLimitParameters* internal_default_instance() {
    return reinterpret_cast<const RegularLimitParameters*>(
        &_RegularLimitParameters_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RegularLimitParameters& a, RegularLimitParameters& b) { a.Swap(&b); }
  inline void Swap(RegularLimitParameters* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegularLimitParameters* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RegularLimitParameters* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RegularLimitParameters>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RegularLimitParameters& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RegularLimitParameters& from) { RegularLimitParameters::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RegularLimitParameters* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "operations_research.RegularLimitParameters"; }

 protected:
  explicit RegularLimitParameters(::google::protobuf::Arena* arena);
  RegularLimitParameters(::google::protobuf::Arena* arena, const RegularLimitParameters& from);
  RegularLimitParameters(::google::protobuf::Arena* arena, RegularLimitParameters&& from) noexcept
      : RegularLimitParameters(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimeFieldNumber = 1,
    kBranchesFieldNumber = 2,
    kFailuresFieldNumber = 3,
    kSolutionsFieldNumber = 4,
    kSmartTimeCheckFieldNumber = 5,
    kCumulativeFieldNumber = 6,
  };
  // int64 time = 1;
  void clear_time() ;
  ::int64_t time() const;
  void set_time(::int64_t value);

  private:
  ::int64_t _internal_time() const;
  void _internal_set_time(::int64_t value);

  public:
  // int64 branches = 2;
  void clear_branches() ;
  ::int64_t branches() const;
  void set_branches(::int64_t value);

  private:
  ::int64_t _internal_branches() const;
  void _internal_set_branches(::int64_t value);

  public:
  // int64 failures = 3;
  void clear_failures() ;
  ::int64_t failures() const;
  void set_failures(::int64_t value);

  private:
  ::int64_t _internal_failures() const;
  void _internal_set_failures(::int64_t value);

  public:
  // int64 solutions = 4;
  void clear_solutions() ;
  ::int64_t solutions() const;
  void set_solutions(::int64_t value);

  private:
  ::int64_t _internal_solutions() const;
  void _internal_set_solutions(::int64_t value);

  public:
  // bool smart_time_check = 5;
  void clear_smart_time_check() ;
  bool smart_time_check() const;
  void set_smart_time_check(bool value);

  private:
  bool _internal_smart_time_check() const;
  void _internal_set_smart_time_check(bool value);

  public:
  // bool cumulative = 6;
  void clear_cumulative() ;
  bool cumulative() const;
  void set_cumulative(bool value);

  private:
  bool _internal_cumulative() const;
  void _internal_set_cumulative(bool value);

  public:
  // @@protoc_insertion_point(class_scope:operations_research.RegularLimitParameters)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RegularLimitParameters& from_msg);
    ::int64_t time_;
    ::int64_t branches_;
    ::int64_t failures_;
    ::int64_t solutions_;
    bool smart_time_check_;
    bool cumulative_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fconstraint_5fsolver_2fsearch_5flimit_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RegularLimitParameters

// int64 time = 1;
inline void RegularLimitParameters::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = ::int64_t{0};
}
inline ::int64_t RegularLimitParameters::time() const {
  // @@protoc_insertion_point(field_get:operations_research.RegularLimitParameters.time)
  return _internal_time();
}
inline void RegularLimitParameters::set_time(::int64_t value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:operations_research.RegularLimitParameters.time)
}
inline ::int64_t RegularLimitParameters::_internal_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_;
}
inline void RegularLimitParameters::_internal_set_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = value;
}

// int64 branches = 2;
inline void RegularLimitParameters::clear_branches() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.branches_ = ::int64_t{0};
}
inline ::int64_t RegularLimitParameters::branches() const {
  // @@protoc_insertion_point(field_get:operations_research.RegularLimitParameters.branches)
  return _internal_branches();
}
inline void RegularLimitParameters::set_branches(::int64_t value) {
  _internal_set_branches(value);
  // @@protoc_insertion_point(field_set:operations_research.RegularLimitParameters.branches)
}
inline ::int64_t RegularLimitParameters::_internal_branches() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.branches_;
}
inline void RegularLimitParameters::_internal_set_branches(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.branches_ = value;
}

// int64 failures = 3;
inline void RegularLimitParameters::clear_failures() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.failures_ = ::int64_t{0};
}
inline ::int64_t RegularLimitParameters::failures() const {
  // @@protoc_insertion_point(field_get:operations_research.RegularLimitParameters.failures)
  return _internal_failures();
}
inline void RegularLimitParameters::set_failures(::int64_t value) {
  _internal_set_failures(value);
  // @@protoc_insertion_point(field_set:operations_research.RegularLimitParameters.failures)
}
inline ::int64_t RegularLimitParameters::_internal_failures() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.failures_;
}
inline void RegularLimitParameters::_internal_set_failures(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.failures_ = value;
}

// int64 solutions = 4;
inline void RegularLimitParameters::clear_solutions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.solutions_ = ::int64_t{0};
}
inline ::int64_t RegularLimitParameters::solutions() const {
  // @@protoc_insertion_point(field_get:operations_research.RegularLimitParameters.solutions)
  return _internal_solutions();
}
inline void RegularLimitParameters::set_solutions(::int64_t value) {
  _internal_set_solutions(value);
  // @@protoc_insertion_point(field_set:operations_research.RegularLimitParameters.solutions)
}
inline ::int64_t RegularLimitParameters::_internal_solutions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.solutions_;
}
inline void RegularLimitParameters::_internal_set_solutions(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.solutions_ = value;
}

// bool smart_time_check = 5;
inline void RegularLimitParameters::clear_smart_time_check() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.smart_time_check_ = false;
}
inline bool RegularLimitParameters::smart_time_check() const {
  // @@protoc_insertion_point(field_get:operations_research.RegularLimitParameters.smart_time_check)
  return _internal_smart_time_check();
}
inline void RegularLimitParameters::set_smart_time_check(bool value) {
  _internal_set_smart_time_check(value);
  // @@protoc_insertion_point(field_set:operations_research.RegularLimitParameters.smart_time_check)
}
inline bool RegularLimitParameters::_internal_smart_time_check() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.smart_time_check_;
}
inline void RegularLimitParameters::_internal_set_smart_time_check(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.smart_time_check_ = value;
}

// bool cumulative = 6;
inline void RegularLimitParameters::clear_cumulative() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cumulative_ = false;
}
inline bool RegularLimitParameters::cumulative() const {
  // @@protoc_insertion_point(field_get:operations_research.RegularLimitParameters.cumulative)
  return _internal_cumulative();
}
inline void RegularLimitParameters::set_cumulative(bool value) {
  _internal_set_cumulative(value);
  // @@protoc_insertion_point(field_set:operations_research.RegularLimitParameters.cumulative)
}
inline bool RegularLimitParameters::_internal_cumulative() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cumulative_;
}
inline void RegularLimitParameters::_internal_set_cumulative(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cumulative_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace operations_research


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ortools_2fconstraint_5fsolver_2fsearch_5flimit_2eproto_2epb_2eh
