// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ortools/math_opt/solvers/glpk.proto
// Protobuf C++ Version: 5.29.3

#ifndef ortools_2fmath_5fopt_2fsolvers_2fglpk_2eproto_2epb_2eh
#define ortools_2fmath_5fopt_2fsolvers_2fglpk_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ortools_2fmath_5fopt_2fsolvers_2fglpk_2eproto OR_PROTO_DLL

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct OR_PROTO_DLL TableStruct_ortools_2fmath_5fopt_2fsolvers_2fglpk_2eproto {
  static const ::uint32_t offsets[];
};
OR_PROTO_DLL extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ortools_2fmath_5fopt_2fsolvers_2fglpk_2eproto;
namespace operations_research {
namespace math_opt {
class GlpkParametersProto;
struct GlpkParametersProtoDefaultTypeInternal;
OR_PROTO_DLL extern GlpkParametersProtoDefaultTypeInternal _GlpkParametersProto_default_instance_;
}  // namespace math_opt
}  // namespace operations_research
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace operations_research {
namespace math_opt {

// ===================================================================


// -------------------------------------------------------------------

class OR_PROTO_DLL GlpkParametersProto final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:operations_research.math_opt.GlpkParametersProto) */ {
 public:
  inline GlpkParametersProto() : GlpkParametersProto(nullptr) {}
  ~GlpkParametersProto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GlpkParametersProto* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GlpkParametersProto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GlpkParametersProto(
      ::google::protobuf::internal::ConstantInitialized);

  inline GlpkParametersProto(const GlpkParametersProto& from) : GlpkParametersProto(nullptr, from) {}
  inline GlpkParametersProto(GlpkParametersProto&& from) noexcept
      : GlpkParametersProto(nullptr, std::move(from)) {}
  inline GlpkParametersProto& operator=(const GlpkParametersProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline GlpkParametersProto& operator=(GlpkParametersProto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GlpkParametersProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const GlpkParametersProto* internal_default_instance() {
    return reinterpret_cast<const GlpkParametersProto*>(
        &_GlpkParametersProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GlpkParametersProto& a, GlpkParametersProto& b) { a.Swap(&b); }
  inline void Swap(GlpkParametersProto* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GlpkParametersProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GlpkParametersProto* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GlpkParametersProto>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GlpkParametersProto& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GlpkParametersProto& from) { GlpkParametersProto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GlpkParametersProto* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "operations_research.math_opt.GlpkParametersProto"; }

 protected:
  explicit GlpkParametersProto(::google::protobuf::Arena* arena);
  GlpkParametersProto(::google::protobuf::Arena* arena, const GlpkParametersProto& from);
  GlpkParametersProto(::google::protobuf::Arena* arena, GlpkParametersProto&& from) noexcept
      : GlpkParametersProto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kComputeUnboundRaysIfPossibleFieldNumber = 1,
  };
  // optional bool compute_unbound_rays_if_possible = 1;
  bool has_compute_unbound_rays_if_possible() const;
  void clear_compute_unbound_rays_if_possible() ;
  bool compute_unbound_rays_if_possible() const;
  void set_compute_unbound_rays_if_possible(bool value);

  private:
  bool _internal_compute_unbound_rays_if_possible() const;
  void _internal_set_compute_unbound_rays_if_possible(bool value);

  public:
  // @@protoc_insertion_point(class_scope:operations_research.math_opt.GlpkParametersProto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GlpkParametersProto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool compute_unbound_rays_if_possible_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fmath_5fopt_2fsolvers_2fglpk_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GlpkParametersProto

// optional bool compute_unbound_rays_if_possible = 1;
inline bool GlpkParametersProto::has_compute_unbound_rays_if_possible() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void GlpkParametersProto::clear_compute_unbound_rays_if_possible() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.compute_unbound_rays_if_possible_ = false;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline bool GlpkParametersProto::compute_unbound_rays_if_possible() const {
  // @@protoc_insertion_point(field_get:operations_research.math_opt.GlpkParametersProto.compute_unbound_rays_if_possible)
  return _internal_compute_unbound_rays_if_possible();
}
inline void GlpkParametersProto::set_compute_unbound_rays_if_possible(bool value) {
  _internal_set_compute_unbound_rays_if_possible(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:operations_research.math_opt.GlpkParametersProto.compute_unbound_rays_if_possible)
}
inline bool GlpkParametersProto::_internal_compute_unbound_rays_if_possible() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.compute_unbound_rays_if_possible_;
}
inline void GlpkParametersProto::_internal_set_compute_unbound_rays_if_possible(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.compute_unbound_rays_if_possible_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace math_opt
}  // namespace operations_research


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ortools_2fmath_5fopt_2fsolvers_2fglpk_2eproto_2epb_2eh
