// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ortools/math_opt/solvers/highs.proto
// Protobuf C++ Version: 5.29.3

#ifndef ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto_2epb_2eh
#define ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto OR_PROTO_DLL

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct OR_PROTO_DLL TableStruct_ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto {
  static const ::uint32_t offsets[];
};
OR_PROTO_DLL extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto;
namespace operations_research {
namespace math_opt {
class HighsOptionsProto;
struct HighsOptionsProtoDefaultTypeInternal;
OR_PROTO_DLL extern HighsOptionsProtoDefaultTypeInternal _HighsOptionsProto_default_instance_;
class HighsOptionsProto_BoolOptionsEntry_DoNotUse;
struct HighsOptionsProto_BoolOptionsEntry_DoNotUseDefaultTypeInternal;
OR_PROTO_DLL extern HighsOptionsProto_BoolOptionsEntry_DoNotUseDefaultTypeInternal _HighsOptionsProto_BoolOptionsEntry_DoNotUse_default_instance_;
class HighsOptionsProto_DoubleOptionsEntry_DoNotUse;
struct HighsOptionsProto_DoubleOptionsEntry_DoNotUseDefaultTypeInternal;
OR_PROTO_DLL extern HighsOptionsProto_DoubleOptionsEntry_DoNotUseDefaultTypeInternal _HighsOptionsProto_DoubleOptionsEntry_DoNotUse_default_instance_;
class HighsOptionsProto_IntOptionsEntry_DoNotUse;
struct HighsOptionsProto_IntOptionsEntry_DoNotUseDefaultTypeInternal;
OR_PROTO_DLL extern HighsOptionsProto_IntOptionsEntry_DoNotUseDefaultTypeInternal _HighsOptionsProto_IntOptionsEntry_DoNotUse_default_instance_;
class HighsOptionsProto_StringOptionsEntry_DoNotUse;
struct HighsOptionsProto_StringOptionsEntry_DoNotUseDefaultTypeInternal;
OR_PROTO_DLL extern HighsOptionsProto_StringOptionsEntry_DoNotUseDefaultTypeInternal _HighsOptionsProto_StringOptionsEntry_DoNotUse_default_instance_;
}  // namespace math_opt
}  // namespace operations_research
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace operations_research {
namespace math_opt {

// ===================================================================


// -------------------------------------------------------------------

class HighsOptionsProto_StringOptionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  HighsOptionsProto_StringOptionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HighsOptionsProto_StringOptionsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit HighsOptionsProto_StringOptionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const HighsOptionsProto_StringOptionsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const HighsOptionsProto_StringOptionsEntry_DoNotUse*>(
        &_HighsOptionsProto_StringOptionsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      82, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class HighsOptionsProto_IntOptionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, ::int32_t,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, ::int32_t,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>;
  HighsOptionsProto_IntOptionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HighsOptionsProto_IntOptionsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit HighsOptionsProto_IntOptionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const HighsOptionsProto_IntOptionsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const HighsOptionsProto_IntOptionsEntry_DoNotUse*>(
        &_HighsOptionsProto_IntOptionsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      74, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class HighsOptionsProto_DoubleOptionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, double,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, double,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>;
  HighsOptionsProto_DoubleOptionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HighsOptionsProto_DoubleOptionsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit HighsOptionsProto_DoubleOptionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const HighsOptionsProto_DoubleOptionsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const HighsOptionsProto_DoubleOptionsEntry_DoNotUse*>(
        &_HighsOptionsProto_DoubleOptionsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      77, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class HighsOptionsProto_BoolOptionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, bool,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_BOOL> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, bool,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>;
  HighsOptionsProto_BoolOptionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HighsOptionsProto_BoolOptionsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit HighsOptionsProto_BoolOptionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const HighsOptionsProto_BoolOptionsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const HighsOptionsProto_BoolOptionsEntry_DoNotUse*>(
        &_HighsOptionsProto_BoolOptionsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      75, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class OR_PROTO_DLL HighsOptionsProto final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:operations_research.math_opt.HighsOptionsProto) */ {
 public:
  inline HighsOptionsProto() : HighsOptionsProto(nullptr) {}
  ~HighsOptionsProto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HighsOptionsProto* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HighsOptionsProto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HighsOptionsProto(
      ::google::protobuf::internal::ConstantInitialized);

  inline HighsOptionsProto(const HighsOptionsProto& from) : HighsOptionsProto(nullptr, from) {}
  inline HighsOptionsProto(HighsOptionsProto&& from) noexcept
      : HighsOptionsProto(nullptr, std::move(from)) {}
  inline HighsOptionsProto& operator=(const HighsOptionsProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline HighsOptionsProto& operator=(HighsOptionsProto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HighsOptionsProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const HighsOptionsProto* internal_default_instance() {
    return reinterpret_cast<const HighsOptionsProto*>(
        &_HighsOptionsProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(HighsOptionsProto& a, HighsOptionsProto& b) { a.Swap(&b); }
  inline void Swap(HighsOptionsProto* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HighsOptionsProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HighsOptionsProto* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HighsOptionsProto>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HighsOptionsProto& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HighsOptionsProto& from) { HighsOptionsProto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HighsOptionsProto* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "operations_research.math_opt.HighsOptionsProto"; }

 protected:
  explicit HighsOptionsProto(::google::protobuf::Arena* arena);
  HighsOptionsProto(::google::protobuf::Arena* arena, const HighsOptionsProto& from);
  HighsOptionsProto(::google::protobuf::Arena* arena, HighsOptionsProto&& from) noexcept
      : HighsOptionsProto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStringOptionsFieldNumber = 1,
    kDoubleOptionsFieldNumber = 2,
    kIntOptionsFieldNumber = 3,
    kBoolOptionsFieldNumber = 4,
  };
  // map<string, string> string_options = 1;
  int string_options_size() const;
  private:
  int _internal_string_options_size() const;

  public:
  void clear_string_options() ;
  const ::google::protobuf::Map<std::string, std::string>& string_options() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_string_options();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_string_options() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_string_options();

  public:
  // map<string, double> double_options = 2;
  int double_options_size() const;
  private:
  int _internal_double_options_size() const;

  public:
  void clear_double_options() ;
  const ::google::protobuf::Map<std::string, double>& double_options() const;
  ::google::protobuf::Map<std::string, double>* mutable_double_options();

  private:
  const ::google::protobuf::Map<std::string, double>& _internal_double_options() const;
  ::google::protobuf::Map<std::string, double>* _internal_mutable_double_options();

  public:
  // map<string, int32> int_options = 3;
  int int_options_size() const;
  private:
  int _internal_int_options_size() const;

  public:
  void clear_int_options() ;
  const ::google::protobuf::Map<std::string, ::int32_t>& int_options() const;
  ::google::protobuf::Map<std::string, ::int32_t>* mutable_int_options();

  private:
  const ::google::protobuf::Map<std::string, ::int32_t>& _internal_int_options() const;
  ::google::protobuf::Map<std::string, ::int32_t>* _internal_mutable_int_options();

  public:
  // map<string, bool> bool_options = 4;
  int bool_options_size() const;
  private:
  int _internal_bool_options_size() const;

  public:
  void clear_bool_options() ;
  const ::google::protobuf::Map<std::string, bool>& bool_options() const;
  ::google::protobuf::Map<std::string, bool>* mutable_bool_options();

  private:
  const ::google::protobuf::Map<std::string, bool>& _internal_bool_options() const;
  ::google::protobuf::Map<std::string, bool>* _internal_mutable_bool_options();

  public:
  // @@protoc_insertion_point(class_scope:operations_research.math_opt.HighsOptionsProto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 4, 4,
      106, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const HighsOptionsProto& from_msg);
    ::google::protobuf::internal::MapField<HighsOptionsProto_StringOptionsEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        string_options_;
    ::google::protobuf::internal::MapField<HighsOptionsProto_DoubleOptionsEntry_DoNotUse, std::string, double,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>
        double_options_;
    ::google::protobuf::internal::MapField<HighsOptionsProto_IntOptionsEntry_DoNotUse, std::string, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>
        int_options_;
    ::google::protobuf::internal::MapField<HighsOptionsProto_BoolOptionsEntry_DoNotUse, std::string, bool,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>
        bool_options_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// HighsOptionsProto

// map<string, string> string_options = 1;
inline int HighsOptionsProto::_internal_string_options_size() const {
  return _internal_string_options().size();
}
inline int HighsOptionsProto::string_options_size() const {
  return _internal_string_options_size();
}
inline void HighsOptionsProto::clear_string_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.string_options_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& HighsOptionsProto::_internal_string_options() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.string_options_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& HighsOptionsProto::string_options() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:operations_research.math_opt.HighsOptionsProto.string_options)
  return _internal_string_options();
}
inline ::google::protobuf::Map<std::string, std::string>* HighsOptionsProto::_internal_mutable_string_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.string_options_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* HighsOptionsProto::mutable_string_options() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:operations_research.math_opt.HighsOptionsProto.string_options)
  return _internal_mutable_string_options();
}

// map<string, double> double_options = 2;
inline int HighsOptionsProto::_internal_double_options_size() const {
  return _internal_double_options().size();
}
inline int HighsOptionsProto::double_options_size() const {
  return _internal_double_options_size();
}
inline void HighsOptionsProto::clear_double_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.double_options_.Clear();
}
inline const ::google::protobuf::Map<std::string, double>& HighsOptionsProto::_internal_double_options() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.double_options_.GetMap();
}
inline const ::google::protobuf::Map<std::string, double>& HighsOptionsProto::double_options() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:operations_research.math_opt.HighsOptionsProto.double_options)
  return _internal_double_options();
}
inline ::google::protobuf::Map<std::string, double>* HighsOptionsProto::_internal_mutable_double_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.double_options_.MutableMap();
}
inline ::google::protobuf::Map<std::string, double>* HighsOptionsProto::mutable_double_options() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:operations_research.math_opt.HighsOptionsProto.double_options)
  return _internal_mutable_double_options();
}

// map<string, int32> int_options = 3;
inline int HighsOptionsProto::_internal_int_options_size() const {
  return _internal_int_options().size();
}
inline int HighsOptionsProto::int_options_size() const {
  return _internal_int_options_size();
}
inline void HighsOptionsProto::clear_int_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.int_options_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::int32_t>& HighsOptionsProto::_internal_int_options() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.int_options_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::int32_t>& HighsOptionsProto::int_options() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:operations_research.math_opt.HighsOptionsProto.int_options)
  return _internal_int_options();
}
inline ::google::protobuf::Map<std::string, ::int32_t>* HighsOptionsProto::_internal_mutable_int_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.int_options_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::int32_t>* HighsOptionsProto::mutable_int_options() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:operations_research.math_opt.HighsOptionsProto.int_options)
  return _internal_mutable_int_options();
}

// map<string, bool> bool_options = 4;
inline int HighsOptionsProto::_internal_bool_options_size() const {
  return _internal_bool_options().size();
}
inline int HighsOptionsProto::bool_options_size() const {
  return _internal_bool_options_size();
}
inline void HighsOptionsProto::clear_bool_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bool_options_.Clear();
}
inline const ::google::protobuf::Map<std::string, bool>& HighsOptionsProto::_internal_bool_options() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bool_options_.GetMap();
}
inline const ::google::protobuf::Map<std::string, bool>& HighsOptionsProto::bool_options() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:operations_research.math_opt.HighsOptionsProto.bool_options)
  return _internal_bool_options();
}
inline ::google::protobuf::Map<std::string, bool>* HighsOptionsProto::_internal_mutable_bool_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.bool_options_.MutableMap();
}
inline ::google::protobuf::Map<std::string, bool>* HighsOptionsProto::mutable_bool_options() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:operations_research.math_opt.HighsOptionsProto.bool_options)
  return _internal_mutable_bool_options();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace math_opt
}  // namespace operations_research


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ortools_2fmath_5fopt_2fsolvers_2fhighs_2eproto_2epb_2eh
